[package]
name = "divviup-android"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate_type = ["cdylib"]

[dependencies]
janus_core = "0.6.8"
janus_messages = "0.6.8"
jni = "0.21.1"
prio = "0.15.3"
rand = "0.8.5"
