[package]
name = "divviup-android"
version = "0.2.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
janus_core = "0.7.51"
janus_messages = "0.7.2"
jni = "0.21.1"
prio = "0.16.7"
rand = "0.8.5"
thiserror = "2.0.11"
