[package]
name = "divviup-android"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate_type = ["cdylib"]

[dependencies]
janus_core = "0.6.32"
janus_messages = "0.6.32"
jni = "0.21.1"
prio = "0.15.5"
rand = "0.8.5"
thiserror = "1.0.61"
