[package]
name = "divviup-android"
version = "0.2.0"
edition = "2021"
publish = false

[lib]
crate_type = ["cdylib"]

[dependencies]
janus_core = "0.7.8"
janus_messages = "0.7.2"
jni = "0.21.1"
prio = "0.16.3"
rand = "0.8.5"
thiserror = "1.0.60"
